# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
project_name: tardigrade
version: 2


before:
  hooks:
    - go mod tidy
builds:
  - main: cmd/distro.go
    id: distro
    binary: distro
    flags:
      - -tags=embedartifacts
    env:
      - CGO_ENABLED=0
    hooks:
      pre:
        - cmd: make download-worker-artifacts
          env:
            - OS={{ .Os }}
            - ARCH={{ .Arch }}
          output: true
    goos:
      - linux
    goarch:
      - arm64
      - amd64
  - main: cmd/masteragent.go
    id: masteragent
    binary: masteragent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

dockers_v2:
  - id: heir-base
    dockerfile: images/base/Dockerfile
    extra_files:
      - images/base/bootstrap.sh
    images:
      - ghcr.io/tardigrade/heir-base
    tags:
      - "{{ .Tag }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64

  - id: heir-controlplane
    dockerfile: images/controlplane/Dockerfile
    ids:
      - masteragent
    extra_files:
      - artifacts/controlplane
    images:
      - ghcr.io/tardigrade/heir-controlplane
    tags:
      - "{{ .Tag }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      BASE_IMAGE: "ghcr.io/tardigrade/heir-base:{{ .Tag }}"
    hooks:
      pre:
        - cmd: make setup-controlplane-artifacts ARCH=amd64
          output: true
        - cmd: make setup-controlplane-artifacts ARCH=arm64
          output: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

