kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |-
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "host.docker.internal"
        - "kind-control-plane"
        - "kubernetes"
        - "kubernetes.default"
        - "kubernetes.default.svc"
        - "kubernetes.default.svc.cluster.local"
        - "localhost"
        - "10.0.2.2"
        - "10.96.0.1"
        - "172.19.0.2"
        - "127.0.0.1"
