apiVersion: controlplane.tardigrade.runtime.io/v1alpha1
kind: Runtime
metadata:
  name: my-cluster
  namespace: default
spec:
  controlPlane:
    heir:
      image: heir-base:v3
    deployment:
      replicas: 1
      serviceAccountName: default
    service:
      serviceType: NodePort


  upstreamCluster:
    apiServer:
      externalAddress: ""   # set if behind a load balancer, e.g. "192.168.1.100"
      sans: []              # extra SANs to add to the apiserver certificate
      extraArgs: {}
    controllerManager:
      extraArgs: {}
    scheduler:
      extraArgs: {}
#    network: {}
    storage:
      type: kine
      kine:
        dataSource: ""
