# Use distroless as minimal base image to package the clusteragent binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/clusteragent /clusteragent


COPY config/clusteragent/crd/bases/clusteragent.tardigrade.runtime.io_workerjointokens.yaml /etc/kubernetes/crd/
COPY config/clusteragent/crd/bases/clusteragent.tardigrade.runtime.io_helmcharts.yaml /etc/kubernetes/crd/

USER 65532:65532

ENTRYPOINT ["/clusteragent"]
