apiVersion: controlplane.tardigrade.runtime.io/v1alpha1
kind: Runtime
metadata:
  name: my-cluster
  namespace: default
spec:
  controlPlane:
    clusterAgent:
      image: localhost:5001/clusteragent:latest
    heir:
      image: localhost:5001/heir:latest
    deployment:
      replicas: 2
      serviceAccountName: default
    service:
      serviceType: NodePort
      apiServerNodePort: 30080
    planeTunnel:
      server:
        image: localhost:5001/heir-tunnel:latest
        deployment:
          replicas: 2
      service:
        serviceType: NodePort
        nodePort: 30081
  cluster:
    apiServer:
      sans: ["master0", "10.0.2.2","integration-test-control-plane"]
      extraArgs:
        advertise-address: "10.0.2.2"
    controllerManager:
      extraArgs: {}
    scheduler:
      extraArgs: {}
    controlPlaneExternalEndpoint:
      apiServer:
        host: "integration-test-control-plane"
        port: 30080
      planeTunnel:
        host: "integration-test-control-plane"
        port: 30081
    storage:
      type: kine
      kine:
        dataSourceRef:
          name: "postgres-credentials"
          key: dsn
    addons:
      helm:
        runtime:
          image: kind-registry:5000/helmer:latest
        charts:
          - name: flannel
            enabled: false
          - name: cilium
            enabled: true
            install:
              chart:
                name: cilium
                repo: https://helm.cilium.io/
                targetNamespace: kube-system
                version: "1.20.0"
                createNamespace: false
              helm:
                version: v3
                backOffLimit: 30
                timeout: 260s
                atomic: true
              runtime:
                image: kind-registry:5000/helmer:latest
                bootstrap: true
          - name: coredns
            override:
              values:
                content: |
                  servers:
                    - zones:
                        - zone: .
                          use_tcp: true
                      port: 53
                      # -- expose the service on a different port
                      # servicePort: 5353
                      # If serviceType is nodePort you can specify nodePort here
                      # nodePort: 30053
                      # hostPort: 53
                      plugins:
                        - name: errors
                        # Serves a /health endpoint on :8080, required for livenessProbe
                        - name: health
                          configBlock: |-
                            lameduck 10s
                        # Serves a /ready endpoint on :8181, required for readinessProbe
                        - name: ready
                        # Required to query kubernetes API for data
                        - name: kubernetes
                          parameters: cluster.local in-addr.arpa ip6.arpa
                          configBlock: |-
                            pods insecure
                            fallthrough in-addr.arpa ip6.arpa
                            ttl 30
                        # Serves a /metrics endpoint on :9153, required for serviceMonitor
                        - name: prometheus
                          parameters: 0.0.0.0:9153
                        - name: forward
                          parameters: . 192.168.65.7
                        - name: cache
                          parameters: 30
                        - name: loop
                        - name: reload
                        - name: loadbalance
