name: Test Chart

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Install kubebuilder
        run: go install sigs.k8s.io/kubebuilder/v4/cmd/kubebuilder@v4.13.1

      - name: Create kind cluster
        run: kind create cluster

      - name: Prepare heir
        run: |
          go mod tidy
          make docker-build IMG=controller:latest
          kind load docker-image controller:latest

      - name: setup Helm
        run: |
          make helm
          make install-helm

      - name: Lint Helm Chart
        run: |
          helm lint ./dist/chart

      - name: Deploy manager via Helm
        run: |
          make helm-deploy IMG=heir:v0.1.0

      - name: Check Helm release status
        run: |
          make helm-status
